[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qqylhkxph3f7t5qxds0h50xl53udnx97evaj8kj2msw6t7smtd27vuvqj5a"]

[[validator_account]]
address = "tnam1q8f8uln5yv9zx7sgyaakc3fzldm42kjg9y7tpej2"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "178.23.126.6:26656"

[validator_account.consensus_key]
pk = "tpknam1qzpkj0e53wslycndcaf7ej4v83pm5ms8fqpe69hnqk6rkyqm302e6myjatx"
authorization = "signam1qrelxuzlnlf40g2e7fuvq85sn45kp7gtt04culjk5h3mgyj3akhqprl0kw5ujs0tgwxy2nud53wvyvtz3p09u2nmqjrafdzg9fflplqtd6r92q"

[validator_account.protocol_key]
pk = "tpknam1qrcz0devql9s4zdtuz7fr3n0wuyuaeydejckyua05w59xed3l4crzumm47p"
authorization = "signam1qpmnvzxr9zn3r4ux3tgq6kpye47d78md3upwg8r8dser4vycsg6mns5whjj0kapfr2mcspm8c653myxst8qjutu5uu26qqqnj7jh54gpat3995"

[validator_account.tendermint_node_key]
pk = "tpknam1qpkwxpk3uz455a6897v68udzt97fv4zppnhn4c77wypqjedg4d6lxy5dzju"
authorization = "signam1qznkfa7ccf7qf80vxacpczfexlu656glgc6su63ls9cyrrp2a38r45w4lgxcdsd7pv3pkluam67y9q8kc5zkttnyk74g8kg0ftsl33cfcx9eqn"

[validator_account.eth_hot_key]
pk = "tpknam1qypdl36m69ucqs75ak632u4j57td6gsds2a64aunz3x0crn6sd7u7pcq4egn8"
authorization = "signam1q9ylsmlnkux7mmlufdyaxkrjy6j8aezvedkcjz7yt605kyncymlgu2q2m037ey4hf6xv2ejlcaq4vkt5uueg729wfum8tpwg5l5f9klzqy67mq35"

[validator_account.eth_cold_key]
pk = "tpknam1qyp859es8j9jryymvzh4hpgnjj83pszzgrqq0jlx8qs8ladg5zxet5stgdltv"
authorization = "signam1qxux2tjyrfun8url5fgyartvp4w8c44gukmshww5ag4995ve5cyukj8lzkr506w03ed0fs5zcjm50zfla5vjgpy5ze0yvxmgqzfzx9z0qyqhmsfv"

[validator_account.metadata]
email = "operations@consensus.finoa.io"
description = "Stake and grow your assets using Finoa's institutional-grade infrastructure."
website = "https://www.finoa.io/staking-delegation"
discord_handle = "finoaconsensusservices"
name = "Finoa Consensus Services"

[validator_account.signatures]
tpknam1qqylhkxph3f7t5qxds0h50xl53udnx97evaj8kj2msw6t7smtd27vuvqj5a = "signam1qry5hcz294xxq65vngvth9hnkfwshn9qd39w6efa0k2xp8ny7fpmw9j6452cv5g4nvpgsdruu4x5j5t6mtq5g2gcue3v65fvjfmxl8cw439j8t"
